# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libxkbcommon

# >> macros
# Conditional building of X11 related things
%bcond_with X11
# << macros

Summary:    X.Org X11 XKB parsing library
Version:    0.4.2
Release:    1
Group:      System/Libraries
License:    MIT
URL:        https://github.com/xkbcommon/libxkbcommon.git
Source0:    %{name}-%{version}.tar.xz
Source100:  libxkbcommon.yaml
Requires:   xorg-x11-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xorg-macros) >= 1.16
BuildRequires:  pkgconfig(xcb-xkb)
BuildRequires:  pkgconfig(xkeyboard-config)
BuildRequires:  libtool
BuildRequires:  bison

%description
%{name} is the X.Org library for compiling XKB maps into formats usable by
the X Server or other display servers.


%package devel
Summary:    X.Org X11 XKB parsing development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
X.Org X11 XKB parsing development package.

%if %{with X11}
%package x11
Summary:        X.Org X11 XKB keymap creation library
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description x11
%{name}-x11 is the X.Org library for creating keymaps by querying the X
server.

%package x11-devel
Summary:        X.Org X11 XKB keymap creation library
Requires:       %{name}-x11%{?_isa} = %{version}-%{release}

%description x11-devel
X.Org X11 XKB keymap creation library development package
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --disable-silent-rules \
    --with-xkb-config-root=/usr/share/X11/xkb \
%if %{with X11}
    --enable-x11
%else
    --disable-x11
%endif

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc COPYING
%{_libdir}/libxkbcommon.so.0
%{_libdir}/libxkbcommon.so.0.0.0
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/xkbcommon/xkbcommon.h
%{_includedir}/xkbcommon/xkbcommon-names.h
%{_includedir}/xkbcommon/xkbcommon-keysyms.h
%{_includedir}/xkbcommon/xkbcommon-compat.h
%{_libdir}/libxkbcommon.so
%{_libdir}/pkgconfig/xkbcommon.pc
# >> files devel
# << files devel

%if %{with X11}
%post x11 -p /sbin/ldconfig
%postun x11 -p /sbin/ldconfig

%files x11
%defattr(-,root,root,-)
%{_libdir}/libxkbcommon-x11.so.0
%{_libdir}/libxkbcommon-x11.so.0.0.0

%files x11-devel
%{_includedir}/xkbcommon/xkbcommon-x11.h
%{_libdir}/libxkbcommon-x11.so
%{_libdir}/pkgconfig/xkbcommon-x11.pc
%endif
