# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libxkbcommon

# >> macros
# Conditional building of X11 related things
%bcond_with X11

%if %{with X11}
%global x11 --enable-x11
%else
%global x11 --disable-x11
%endif
# << macros

Summary:    Xorg X11 common xkb library
Version:    0.4.2
Release:    1
Group:      System/Libraries
License:    MIT
URL:        https://github.com/xkbcommon/libxkbcommon.git
Source0:    %{name}-%{version}.tar.xz
Source100:  libxkbcommon.yaml
Requires:   xorg-x11-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xorg-macros) >= 1.16
BuildRequires:  pkgconfig(xcb-xkb)
BuildRequires:  libtool
BuildRequires:  bison

%description
Xorg X11 common xkb library


%package devel
Summary:    Xorg X11 common xkb libray
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
xkb development libraries.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --with-xkb-config-root=/usr/share/X11/xkb \
    %{?x11}

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libxkbcommon.so.0
%{_libdir}/libxkbcommon.so.0.0.0
# >> files
%if %{with X11}
%{_libdir}/libxkbcommon-x11.so.0
%{_libdir}/libxkbcommon-x11.so.0.0.0
%endif
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/xkbcommon/xkbcommon.h
%{_includedir}/xkbcommon/xkbcommon-names.h
%{_includedir}/xkbcommon/xkbcommon-keysyms.h
%{_includedir}/xkbcommon/xkbcommon-compat.h
%{_libdir}/libxkbcommon.so
%{_libdir}/pkgconfig/xkbcommon.pc
# >> files devel
%if %{with X11}
%{_includedir}/xkbcommon/xkbcommon-x11.h
%{_libdir}/libxkbcommon-x11.so
%{_libdir}/pkgconfig/xkbcommon-x11.pc
%endif
# << files devel
